/**
 * Vaccination record PDF generation — farm and personal modes.
 *
 * Farm:     professional livestock health record, grouped by animal,
 *           green theme, includes tag, species, herd, batch numbers.
 *
 * Personal: individual + dependent + pet vaccination summary,
 *           blue theme, includes authentication status and expiry.
 */

import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { UserVaccine } from '../types/vaccine'
import type { Dependent }    from '../types/dependent'
import type { Pet, PetVaccine } from '../types/pet'
import type { FarmAnimal, FarmVaccine } from '../types/farm'
import { FARM_SPECIES_LABELS }  from '../types/farm'
import { PET_SPECIES_LABELS }   from '../types/pet'

// ── Shared constants ──────────────────────────────────────────────────────────

const MARGIN  = 14          // mm left/right
const PW      = 210         // A4 width mm
const CONTENT = PW - MARGIN * 2   // 182 mm

const GREEN   = [22, 163, 74]   as [number, number, number]
const GREEN_D = [20, 83, 45]    as [number, number, number]
const GREEN_L = [220, 252, 231] as [number, number, number]
const BLUE    = [37, 99, 235]   as [number, number, number]
const BLUE_D  = [30, 64, 175]   as [number, number, number]
const BLUE_L  = [219, 234, 254] as [number, number, number]
const GREY    = [107, 114, 128] as [number, number, number]
const GREY_L  = [243, 244, 246] as [number, number, number]
const BLACK   = [17, 24, 39]    as [number, number, number]
const WHITE   = [255, 255, 255] as [number, number, number]

function fmt(iso: string | null | undefined): string {
  if (!iso) return '—'
  try {
    const [y, m, d] = iso.slice(0, 10).split('-')
    return `${d}/${m}/${y}`
  } catch { return iso }
}

function today(): string {
  return fmt(new Date().toISOString().slice(0, 10))
}

function addPageNumbers(doc: jsPDF) {
  const total = doc.getNumberOfPages()
  for (let i = 1; i <= total; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(...GREY)
    doc.text(
      `Page ${i} of ${total}   ·   Generated by VacciPass   ·   ${today()}`,
      PW / 2, 290, { align: 'center' },
    )
  }
}

// ── Header banner ─────────────────────────────────────────────────────────────

function drawHeader(
  doc: jsPDF,
  title: string,
  subtitle: string,
  accentColor: [number, number, number],
  accentDark: [number, number, number],
): number {
  // Full-width banner
  doc.setFillColor(...accentColor)
  doc.rect(0, 0, PW, 38, 'F')

  // Left accent strip
  doc.setFillColor(...accentDark)
  doc.rect(0, 0, 5, 38, 'F')

  // Shield icon (simplified — draw a rounded rect + tick)
  doc.setFillColor(...WHITE)
  doc.roundedRect(MARGIN, 8, 16, 18, 3, 3, 'F')
  doc.setDrawColor(...accentColor)
  doc.setLineWidth(1.5)
  doc.setDrawColor(...accentDark)
  // Tick mark
  doc.line(MARGIN + 4, 18, MARGIN + 7, 22)
  doc.line(MARGIN + 7, 22, MARGIN + 14, 14)

  // Title
  doc.setTextColor(...WHITE)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text(title, MARGIN + 20, 17)

  // Subtitle
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text(subtitle, MARGIN + 20, 26)

  // Generated date (right-aligned)
  doc.setFontSize(8)
  doc.text(`Generated: ${today()}`, PW - MARGIN, 26, { align: 'right' })

  return 44  // Y position after header
}

// ── Section heading ───────────────────────────────────────────────────────────

function drawSectionHeading(
  doc: jsPDF,
  y: number,
  text: string,
  bgColor: [number, number, number],
  lightColor: [number, number, number],
): number {
  doc.setFillColor(...lightColor)
  doc.roundedRect(MARGIN, y, CONTENT, 8, 1.5, 1.5, 'F')
  doc.setFillColor(...bgColor)
  doc.roundedRect(MARGIN, y, 3, 8, 1, 1, 'F')
  doc.setTextColor(...bgColor)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.text(text.toUpperCase(), MARGIN + 6, y + 5.5)
  return y + 12
}

// ── Stat pill row ─────────────────────────────────────────────────────────────

function drawStats(
  doc: jsPDF,
  y: number,
  stats: Array<{ label: string; value: string | number }>,
  accentColor: [number, number, number],
): number {
  const w = CONTENT / stats.length
  stats.forEach((s, i) => {
    const x = MARGIN + i * w
    doc.setFillColor(...GREY_L)
    doc.roundedRect(x + 1, y, w - 2, 14, 2, 2, 'F')
    doc.setTextColor(...accentColor)
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text(String(s.value), x + w / 2, y + 7.5, { align: 'center' })
    doc.setTextColor(...GREY)
    doc.setFontSize(7)
    doc.setFont('helvetica', 'normal')
    doc.text(s.label.toUpperCase(), x + w / 2, y + 12.5, { align: 'center' })
  })
  return y + 18
}

// ── Animal info block (farm) ──────────────────────────────────────────────────

function drawAnimalBlock(doc: jsPDF, y: number, animal: FarmAnimal): number {
  doc.setFillColor(240, 253, 244)  // green-50
  doc.roundedRect(MARGIN, y, CONTENT, 14, 2, 2, 'F')

  doc.setTextColor(...GREEN_D)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  const label = `${animal.tagNumber}${animal.name ? '  ·  ' + animal.name : ''}`
  doc.text(label, MARGIN + 4, y + 6)

  doc.setTextColor(...GREY)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  const details = [
    FARM_SPECIES_LABELS[animal.species] ?? animal.species,
    animal.herd    ? `Herd: ${animal.herd}`    : null,
    animal.breed   ? animal.breed              : null,
    animal.sex     ? animal.sex                : null,
    animal.dateOfBirth ? `DOB: ${fmt(animal.dateOfBirth)}` : null,
    animal.chipId  ? `Chip: ${animal.chipId}`  : null,
  ].filter(Boolean).join('   ')
  doc.text(details, MARGIN + 4, y + 12)

  return y + 18
}

// ── Entity block (personal) ───────────────────────────────────────────────────

function drawPersonBlock(
  doc: jsPDF, y: number,
  name: string, detail: string,
  accentColor: [number, number, number],
): number {
  doc.setFillColor(239, 246, 255)  // blue-50
  doc.roundedRect(MARGIN, y, CONTENT, 12, 2, 2, 'F')
  doc.setFillColor(...accentColor)
  doc.roundedRect(MARGIN, y, 3, 12, 1, 1, 'F')
  doc.setTextColor(...BLUE_D)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text(name, MARGIN + 7, y + 5.5)
  doc.setTextColor(...GREY)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  if (detail) doc.text(detail, MARGIN + 7, y + 10)
  return y + 16
}

// ── Check remaining page space ────────────────────────────────────────────────

function checkPageBreak(doc: jsPDF, y: number, needed = 30): number {
  if (y + needed > 275) {
    doc.addPage()
    return 14
  }
  return y
}

// ─────────────────────────────────────────────────────────────────────────────
//  FARM REPORT
// ─────────────────────────────────────────────────────────────────────────────

export interface FarmAnimalRecord {
  animal:   FarmAnimal
  vaccines: FarmVaccine[]
}

export interface FarmReportInput {
  ownerName:   string
  animals:     FarmAnimalRecord[]
}

export function generateFarmReport(input: FarmReportInput): void {
  const { ownerName, animals } = input
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })

  const totalVax  = animals.reduce((s, a) => s + a.vaccines.length, 0)
  const herds     = Array.from(new Set(animals.map(a => a.animal.herd ?? 'Ungrouped')))

  let y = drawHeader(
    doc,
    'LIVESTOCK VACCINATION RECORD',
    `Owner: ${ownerName}`,
    GREEN, GREEN_D,
  )

  y = drawStats(doc, y, [
    { label: 'Animals',        value: animals.length },
    { label: 'Herds',          value: herds.length },
    { label: 'Vaccine Records',value: totalVax },
  ], GREEN)

  y += 4

  // Group by herd
  const byHerd = new Map<string, FarmAnimalRecord[]>()
  animals.forEach(rec => {
    const h = rec.animal.herd ?? 'Ungrouped'
    if (!byHerd.has(h)) byHerd.set(h, [])
    byHerd.get(h)!.push(rec)
  })

  for (const [herd, recs] of byHerd.entries()) {
    y = checkPageBreak(doc, y, 24)
    y = drawSectionHeading(doc, y, herd, GREEN, GREEN_L)

    for (const rec of recs) {
      y = checkPageBreak(doc, y, 40)
      y = drawAnimalBlock(doc, y, rec.animal)

      if (rec.vaccines.length === 0) {
        doc.setTextColor(...GREY)
        doc.setFontSize(8)
        doc.setFont('helvetica', 'italic')
        doc.text('No vaccination records', MARGIN + 4, y)
        y += 8
        continue
      }

      autoTable(doc, {
        startY: y,
        margin: { left: MARGIN, right: MARGIN },
        head: [['Date Admin', 'Vaccine Name', 'Disease Target', 'Clinic / Vet', 'Batch #', 'Expiry']],
        body: rec.vaccines.map(v => [
          fmt(v.date_administration),
          v.vaccine_name,
          v.disease_target ?? '—',
          [v.Clinic, v.Doctor].filter(Boolean).join(' · ') || '—',
          v.batch_number ?? '—',
          fmt(v.Expiration_date),
        ]),
        styles:     { fontSize: 7.5, cellPadding: 2.5, textColor: BLACK },
        headStyles: { fillColor: GREEN, textColor: WHITE, fontSize: 8, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: GREY_L },
        columnStyles: {
          0: { cellWidth: 22 },
          1: { cellWidth: 40 },
          2: { cellWidth: 35 },
          3: { cellWidth: 35 },
          4: { cellWidth: 22 },
          5: { cellWidth: 22 },
        },
        tableLineColor: [209, 213, 219],
        tableLineWidth: 0.2,
        didDrawPage: () => {},
      })

      y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6
    }

    y += 4
  }

  addPageNumbers(doc)
  doc.save(`livestock_vaccination_record_${new Date().toISOString().slice(0, 10)}.pdf`)
}

// ─────────────────────────────────────────────────────────────────────────────
//  PERSONAL REPORT
// ─────────────────────────────────────────────────────────────────────────────

export interface PersonalReportSelf {
  name:     string
  vaccines: UserVaccine[]
}
export interface PersonalReportDependent {
  dependent: Dependent
  vaccines:  UserVaccine[]
}
export interface PersonalReportPet {
  pet:      Pet
  vaccines: PetVaccine[]
}

export interface PersonalReportInput {
  self?:       PersonalReportSelf
  dependents?: PersonalReportDependent[]
  pets?:       PersonalReportPet[]
}

export function generatePersonalReport(input: PersonalReportInput): void {
  const { self, dependents = [], pets = [] } = input
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })

  const ownerName  = self?.name ?? 'Vaccination Record'
  const totalVax   =
    (self?.vaccines.length ?? 0) +
    dependents.reduce((s, d) => s + d.vaccines.length, 0) +
    pets.reduce((s, p) => s + p.vaccines.length, 0)

  let y = drawHeader(
    doc,
    'VACCINATION RECORD',
    ownerName,
    BLUE, BLUE_D,
  )

  y = drawStats(doc, y, [
    { label: 'Total Records', value: totalVax },
    { label: 'Dependents',    value: dependents.length },
    { label: 'Pets',          value: pets.length },
  ], BLUE)

  y += 4

  // ── Self vaccines ────────────────────────────────────────────────────────
  if (self) {
    y = checkPageBreak(doc, y, 24)
    y = drawSectionHeading(doc, y, 'My Vaccines', BLUE, BLUE_L)
    y = drawPersonBlock(doc, y, self.name, 'Personal vaccines', BLUE)

    if (self.vaccines.length === 0) {
      doc.setTextColor(...GREY)
      doc.setFontSize(8)
      doc.setFont('helvetica', 'italic')
      doc.text('No vaccination records', MARGIN + 4, y)
      y += 8
    } else {
      autoTable(doc, {
        startY: y,
        margin: { left: MARGIN, right: MARGIN },
        head: [['Date Admin', 'Vaccine Name', 'Clinic / Dr', 'Auth Status', 'Expiry']],
        body: self.vaccines.map(v => [
          fmt(v.date_administration),
          v.vaccine_name,
          [v.Clinic, v.Doctor].filter(Boolean).join(' · ') || '—',
          v.Authenticated ? 'Verified ✓' : v.pending_validation ? 'Pending' : 'Unverified',
          fmt(v.Expiration_date),
        ]),
        styles:     { fontSize: 7.5, cellPadding: 2.5, textColor: BLACK },
        headStyles: { fillColor: BLUE, textColor: WHITE, fontSize: 8, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: GREY_L },
        columnStyles: {
          0: { cellWidth: 24 },
          1: { cellWidth: 68 },
          2: { cellWidth: 48 },
          3: { cellWidth: 22 },
          4: { cellWidth: 20 },
        },
        tableLineColor: [209, 213, 219],
        tableLineWidth: 0.2,
      })
      y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8
    }
  }

  // ── Dependents ───────────────────────────────────────────────────────────
  if (dependents.length > 0) {
    y = checkPageBreak(doc, y, 24)
    y = drawSectionHeading(doc, y, 'Dependents', BLUE, BLUE_L)

    for (const dep of dependents) {
      y = checkPageBreak(doc, y, 36)
      const detail = dep.dependent.dateOfBirth
        ? `DOB: ${fmt(dep.dependent.dateOfBirth)}`
        : ''
      y = drawPersonBlock(doc, y, dep.dependent.name, detail, BLUE)

      if (dep.vaccines.length === 0) {
        doc.setTextColor(...GREY)
        doc.setFontSize(8)
        doc.setFont('helvetica', 'italic')
        doc.text('No vaccination records', MARGIN + 4, y)
        y += 8
        continue
      }

      autoTable(doc, {
        startY: y,
        margin: { left: MARGIN, right: MARGIN },
        head: [['Date Admin', 'Vaccine Name', 'Clinic / Dr', 'Auth Status', 'Expiry']],
        body: dep.vaccines.map(v => [
          fmt(v.date_administration),
          v.vaccine_name,
          [v.Clinic, v.Doctor].filter(Boolean).join(' · ') || '—',
          v.Authenticated ? 'Verified ✓' : v.pending_validation ? 'Pending' : 'Unverified',
          fmt(v.Expiration_date),
        ]),
        styles:     { fontSize: 7.5, cellPadding: 2.5, textColor: BLACK },
        headStyles: { fillColor: BLUE, textColor: WHITE, fontSize: 8, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: GREY_L },
        columnStyles: {
          0: { cellWidth: 24 },
          1: { cellWidth: 68 },
          2: { cellWidth: 48 },
          3: { cellWidth: 22 },
          4: { cellWidth: 20 },
        },
        tableLineColor: [209, 213, 219],
        tableLineWidth: 0.2,
      })
      y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8
    }
  }

  // ── Pets ─────────────────────────────────────────────────────────────────
  if (pets.length > 0) {
    y = checkPageBreak(doc, y, 24)
    y = drawSectionHeading(doc, y, 'Pets', BLUE, BLUE_L)

    for (const entry of pets) {
      y = checkPageBreak(doc, y, 36)
      const speciesLabel = PET_SPECIES_LABELS[entry.pet.species] ?? entry.pet.species
      const detail = [
        speciesLabel,
        entry.pet.breed ?? null,
        entry.pet.dateOfBirth ? `DOB: ${fmt(entry.pet.dateOfBirth)}` : null,
      ].filter(Boolean).join('   ·   ')
      y = drawPersonBlock(doc, y, entry.pet.name, detail, BLUE)

      if (entry.vaccines.length === 0) {
        doc.setTextColor(...GREY)
        doc.setFontSize(8)
        doc.setFont('helvetica', 'italic')
        doc.text('No vaccination records', MARGIN + 4, y)
        y += 8
        continue
      }

      autoTable(doc, {
        startY: y,
        margin: { left: MARGIN, right: MARGIN },
        head: [['Date Admin', 'Vaccine Name', 'Disease Target', 'Clinic / Vet', 'Expiry']],
        body: entry.vaccines.map(v => [
          fmt(v.date_administration),
          v.vaccine_name,
          v.disease_target ?? '—',
          [v.Clinic, v.Doctor].filter(Boolean).join(' · ') || '—',
          fmt(v.Expiration_date),
        ]),
        styles:     { fontSize: 7.5, cellPadding: 2.5, textColor: BLACK },
        headStyles: { fillColor: BLUE, textColor: WHITE, fontSize: 8, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: GREY_L },
        columnStyles: {
          0: { cellWidth: 24 },
          1: { cellWidth: 50 },
          2: { cellWidth: 40 },
          3: { cellWidth: 48 },
          4: { cellWidth: 20 },
        },
        tableLineColor: [209, 213, 219],
        tableLineWidth: 0.2,
      })
      y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8
    }
  }

  addPageNumbers(doc)
  doc.save(`vaccination_record_${new Date().toISOString().slice(0, 10)}.pdf`)
}
